---
- name: Backup MC Containers to MinIO
  hosts: mc-host
  vars:
    mc_servers:
      - name: mc1
        container: mc_server_1-mc1-1
        path: /home/peter/mc1
      - name: mc2
        container: mc_server_2-mc2-1
        path: /home/peter/mc2
      - name: mc3
        container: mc_server_3-mc3-1
        path: /home/peter/mc3

    minio_alias: "minio"
    minio_bucket: "mc-backups"

  tasks:

    - name: Create temporary backup directory
      file:
        path: /tmp/mc-backups
        state: directory
        mode: '0755'

    - name: Archive each MC container data
      archive:
        path: "{{ item.path }}"
        dest: "/tmp/mc-backups/{{ item.name }}.tar.gz"
        format: gz
      loop: "{{ mc_servers }}"

    - name: Upload backup to MinIO (versioned)
      command: >
        mc cp /tmp/mc-backups/{{ item.name }}.tar.gz
        {{ minio_alias }}/{{ minio_bucket }}/{{ item.name }}/world.tar.gz
      loop: "{{ mc_servers }}"

    - name: Clean up temporary backup files
      file:
        path: "/tmp/mc-backups/{{ item.name }}.tar.gz"
        state: absent
      loop: "{{ mc_servers }}"
