---
- name: Backup MC worlds to MinIO
  hosts: mc-host

  vars:
    mc_servers:
      - name: mc1
        path: /home/peter/mc1/world
      - name: mc2
        path: /home/peter/mc2/world
      - name: mc3
        path: /home/peter/mc3/world

    minio_alias: "minio"
    minio_bucket: "mc-backups"

  tasks:

    - name: Create temporary backup directory
      file:
        path: /tmp/mc-backups
        state: directory

    - name: Tar only the world folder
      archive:
        path: "{{ item.path }}"
        dest: "/tmp/mc-backups/{{ item.name }}-world.tar.gz"
        format: gz
      loop: "{{ mc_servers }}"

    - name: Upload world backup to MinIO
      command: >
        mc cp /tmp/mc-backups/{{ item.name }}-world.tar.gz
        {{ minio_alias }}/{{ minio_bucket }}/{{ item.name }}/world.tar.gz
      loop: "{{ mc_servers }}"

    - name: Clean up temporary files
      file:
        path: "/tmp/mc-backups/{{ item.name }}-world.tar.gz"
        state: absent
      loop: "{{ mc_servers }}"
