
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"  # Web UI accessible at http://localhost:8080
    volumes:
      - /home/peter:/srv         



