version: '3'

services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=America/New_York # Set your desired timezone
    volumes:
      - /home/peter/homarr:/app/data/configs


