version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/peter/jenkins-controller:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


# run the docker run commands on other machines to make them agents:
# docker pull alpine/socat
# $ docker run -d --restart=always \
#     -p 127.0.0.1:2376:2375 \
#     -v /var/run/docker.sock:/var/run/docker.sock \
#     alpine/socat \
#     tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
