version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25566:25565
    environment:
      EULA: "TRUE"
      # MEMORY: "6GB"
      #JVM_XX_OPTS: "-XX:MaxRAMPercentage=100"
      
      
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/peter/mc_server2:/data


