
services:
  mc-server1: 
    image: itzg/minecraft-server
    ports: 
      - 25567:25565
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      # TYPE: "PAPER"
      USE_AIKAR_FLAGS: "TRUE" 

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /home/peter/main_mc_server:/data:rw
