services:
  metube:
    container_name: metube
    image: alexta69/metube:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - CUSTOM_DIRS=true
      - CREATE_CUSTOM_DIRS=true
      - DOWNLOAD_MODE=limited
      - MAX_CONCURRENT_DOWNLOADS=3
    volumes:
      - /mnt/Stripe1TB/media/youtube_videos:/downloads
    ports:
      - "8501:8081"
    restart: unless-stopped
    mem_limit: 1g