version: "3.5"

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGO
    volumes:
      - type: bind
        source: /home/peter/mongodb/data
        target: /data/db
      - type: bind
        source: /home/peter/mongodb/config
        target: /data/configdb
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - MONGO
    depends_on:
      - mongo
      
      
# source: https://gist.github.com/adamelliotfields/cd49f056deab05250876286d7657dc4b

networks:
  MONGO:
    name: MONGO
