---
- name: Monitor Disk Usage on Docker VMs
  hosts: docker-vms
  become: yes
  vars:
    disk_threshold: "{{ (DISK_USAGE_THRESHOLD | default('85')) | int }}"
    alert_email: "{{ ALERT_EMAIL }}"

  tasks:
    - name: Get disk usage percentage for root filesystem
      shell: df -h / | awk 'NR==2 {print $5}' | sed 's/%//'
      register: disk_usage
      changed_when: false

    - name: Get disk usage details
      shell: df -h /
      register: disk_details
      changed_when: false

    - name: Convert disk usage to integer
      set_fact:
        disk_usage_int: "{{ disk_usage.stdout | int }}"

    - name: Display disk usage
      debug:
        msg: "{{ inventory_hostname }} ({{ ansible_host }}): {{ disk_usage_int }}% used"

    - name: Check if disk usage exceeds threshold
      set_fact:
        disk_over_threshold: "{{ disk_usage_int >= disk_threshold }}"

    - name: Send email alert if disk usage exceeds threshold
      when: disk_over_threshold | bool
      mail:
        to: "{{ alert_email }}"
        subject: "Disk Usage Alert: {{ inventory_hostname }} ({{ ansible_host }})"
        body: |
          Disk usage on {{ inventory_hostname }} ({{ ansible_host }}) is {{ disk_usage_int }}%
          
          Threshold: {{ disk_threshold }}%
          
          Disk Details:
          {{ disk_details.stdout }}
          
          Please investigate and free up space.
      ignore_errors: yes

    - name: Fail if disk usage exceeds threshold
      when: disk_over_threshold | bool
      fail:
        msg: "Disk usage on {{ inventory_hostname }} is {{ disk_usage_int }}%, exceeding threshold of {{ disk_threshold }}%"
