version: '3'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: iamroot6025
    volumes:
      - /home/peter/pgAdmin4:/var/lib/pgadmin
    ports:
      - 5050:80
