version: '3'

services:
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - /home/peter/redisInsights:/db

