---
- name: Restore a single Minecraft world from MinIO
  hosts: mc-host
  become: yes

  vars:
    mc_servers:
      mc1:
        container: "mc_server_1-mc1-1"
      mc2:
        container: "mc_server_2-mc2-1"
      mc3:
        container: "mc_server_3-mc3-1"

  tasks:

    - name: Ensure server_name is valid
      ansible.builtin.fail:
        msg: "Must pass server_name=mc1|mc2|mc3"
      when: server_name is not defined or server_name not in mc_servers

    - name: Stop container
      ansible.builtin.command: docker stop {{ mc_servers[server_name].container }}
      ignore_errors: yes

    - name: Remove current world folder
      ansible.builtin.file:
        path: "{{ backup_root }}/{{ server_name }}/world"
        state: absent

    - name: Recreate empty world folder
      ansible.builtin.file:
        path: "{{ backup_root }}/{{ server_name }}/world"
        state: directory
        owner: peter
        group: peter
        mode: "0755"

    - name: Check if backup exists
      ansible.builtin.command: >
        mc ls {{ minio_alias }}/{{ minio_bucket }}/{{ server_name }}/world.tar.gz
      register: world_exists
      failed_when: world_exists.rc != 0

    - name: Download world backup
      ansible.builtin.command: >
        mc cp {{ minio_alias }}/{{ minio_bucket }}/{{ server_name }}/world.tar.gz
        {{ backup_root }}/{{ server_name }}/world.tar.gz

    - name: Extract world
      ansible.builtin.unarchive:
        src: "{{ backup_root }}/{{ server_name }}/world.tar.gz"
        dest: "{{ backup_root }}/{{ server_name }}"
        remote_src: yes

    - name: Start container
      ansible.builtin.command: docker start {{ mc_servers[server_name].container }}
