---
- name: Restore Minecraft world from MinIO
  hosts: minecraft
  become: yes
  vars:
    minio_alias: "mc1"
    bucket_name: "minecraft-backups"
    server_name: ""   # Pass via extra vars, e.g.:  server_name=survival

  tasks:

    - name: Fail if server_name not provided
      fail:
        msg: "You must provide server_name=<world> via Extra Vars."
      when: server_name == ""

    - name: Ensure mc alias exists
      ansible.builtin.command: >
        mc alias set {{ minio_alias }} {{ minio_url }} {{ minio_access_key }} {{ minio_secret_key }}
      register: alias_result
      changed_when: "'Added' in alias_result.stdout"

    - name: Download backup from MinIO
      ansible.builtin.command: >
        mc cp {{ minio_alias }}/{{ bucket_name }}/{{ server_name }}/world.tar.gz /tmp/world.tar.gz
      register: download_result
      changed_when: "'...'" not in download_result.stdout

    - name: Stop Minecraft service
      ansible.builtin.systemd:
        name: minecraft@{{ server_name }}
        state: stopped

    - name: Remove current world directory
      ansible.builtin.file:
        path: /opt/minecraft/{{ server_name }}/world
        state: absent

    - name: Extract world backup
      ansible.builtin.unarchive:
        src: /tmp/world.tar.gz
        dest: /opt/minecraft/{{ server_name }}
        remote_src: yes

    - name: Fix ownership
      ansible.builtin.file:
        path: /opt/minecraft/{{ server_name }}
        owner: minecraft
        group: minecraft
        recurse: yes

    - name: Start Minecraft service
      ansible.builtin.systemd:
        name: minecraft@{{ server_name }}
        state: started

    - name: Cleanup temp file
      ansible.builtin.file:
        path: /tmp/world.tar.gz
        state: absent
