---
- name: Restore MC servers from MinIO backups
  hosts: mc-host
  become: yes

  vars:
    minio_alias: "minio"
    bucket_name: "mc-backups"
    restore_base_path: "/home/peter"
    mc_servers:
      - name: "mc1"
        container: "mc_server_1-mc1-1"
      - name: "mc2"
        container: "mc_server_2-mc2-1"
      - name: "mc3"
        container: "mc_server_3-mc3-1"

  tasks:

    - name: Ensure mc alias for MinIO exists
      ansible.builtin.command: >
        mc alias set {{ minio_alias }}
        http://10.0.220.145:9000
        {{ lookup('env', 'MINIO_ACCESS_KEY') }}
        {{ lookup('env', 'MINIO_SECRET_KEY') }}
      register: alias_set
      failed_when: false
      changed_when: "'Added' in alias_set.stdout"

    - name: Restore each MC server
      loop: "{{ mc_servers }}"
      block:

        - name: Stop container
          ansible.builtin.command: docker stop {{ item.container }}
          ignore_errors: yes

        - name: Ensure restore temp directory exists
          ansible.builtin.file:
            path: "{{ restore_base_path }}/{{ item.name }}"
            state: directory
            owner: peter
            group: peter
            mode: "0755"

        - name: Download latest backup from MinIO
          ansible.builtin.command: >
            mc cp {{ minio_alias }}/{{ bucket_name }}/{{ item.name }}.tar.gz
            {{ restore_base_path }}/{{ item.name }}/backup.tar.gz

        - name: Remove current data directory
          ansible.builtin.file:
            path: "{{ restore_base_path }}/{{ item.name }}"
            state: absent

        - name: Re-create empty directory
          ansible.builtin.file:
            path: "{{ restore_base_path }}/{{ item.name }}"
            state: directory
            owner: peter
            group: peter
            mode: "0755"

        - name: Extract backup into directory
          ansible.builtin.unarchive:
            src: "{{ restore_base_path }}/{{ item.name }}/backup.tar.gz"
            dest: "{{ restore_base_path }}/{{ item.name }}"
            remote_src: yes

        - name: Start container
          ansible.builtin.command: docker start {{ item.container }}
