version: '3'
services:
  vaultwarden:
    restart: unless-stopped
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /home/peter/vaultwarden:/data/
    ports:
      - 7565:80
